### ISSUE TITLE
read_bim swap ref and alt?

### ISSUE THREAD

**Issue by zjppdozen** [OchoaLab/genio#13]
Hello, 

I noticed there is a recent update in the genio package. In this version (v1.1.1), the read_bim function reads the bim file using the following column sequence: Chr, id, pos, pos, **_alt, ref._** 

But in the previous version (v1.0.25 and earlier), the read_bim function read bim file using the column sequence: Chr, id, pos, pos, _**ref, alt.**_ 

You may notice the columns for the ref and alt allele have swapped between the old and new function of read_bim. This creates confusion when I run analyses for my data. For example, for a single SNP rs7412, when I use the old read_bim function to import the bim file, the ref allele is T, and the alt allele is C. But when I use the most recent version of read_bim to import data for the same SNP, the ref allele is C, and the alt allele is T.

Could you comment on why in the newest version of the R package, you swap the column sequence of alt and ref?

Thanks.

**Comment by alexviiia** [comment]
The change was documented in `NEWS.md`, the revelant entry reproduced below.  The short answer is that the previous version identified ref and alt incorrectly, it was the opposite of what VCF and newer plink2 formats report.  I'm sorry I had to make that change, but the earlier version was just wrong.

genio 1.1.0.9000 (2022-04-20)

- Functions read_bim, write_bim, and geno_to_char: reversed columns "ref" and "alt" in BIM table
  - Previous versions treated the first allele column from the (headerless) BIM file as "ref", second as "alt", in part because the plink 1.9 documentation was unclear about their identities (they were simply called alleles "1/clear bits/usually minor" and "2/set bits/usually major").
  - New version has first allele column as "alt", second as "ref", after seeing plink 2.0 documentation define them explicitly this way, and after noticing reverse correspondence with ref/alt values in VCF files (thanks Ochoa Lab members Amika Sood and Tiffany Tu for reporting these issues!).
  - read_bim now returns a tibble with allele names "alt" and "ref" in that order (columns still ordered as they appear in input file)
  - write_bim writes tables with column "alt" before "ref"
  - geno_to_char reverses the role of "alt" and "ref" correspondingly so that the output remains the same as before these changes (the original outputs were correct as validated against the plink1 "ped" text genotypes).
  - All documentation was updated to reflect these changes.

**Comment by zjppdozen** [comment]
> The change was documented in `NEWS.md`, the revelant entry reproduced below. The short answer is that the previous version identified ref and alt incorrectly, it was the opposite of what VCF and newer plink2 formats report. I'm sorry I had to make that change, but the earlier version was just wrong.
> 
> genio 1.1.0.9000 (2022-04-20)
> 
> * Functions read_bim, write_bim, and geno_to_char: reversed columns "ref" and "alt" in BIM table
>   
>   * Previous versions treated the first allele column from the (headerless) BIM file as "ref", second as "alt", in part because the plink 1.9 documentation was unclear about their identities (they were simply called alleles "1/clear bits/usually minor" and "2/set bits/usually major").
>   * New version has first allele column as "alt", second as "ref", after seeing plink 2.0 documentation define them explicitly this way, and after noticing reverse correspondence with ref/alt values in VCF files (thanks Ochoa Lab members Amika Sood and Tiffany Tu for reporting these issues!).
>   * read_bim now returns a tibble with allele names "alt" and "ref" in that order (columns still ordered as they appear in input file)
>   * write_bim writes tables with column "alt" before "ref"
>   * geno_to_char reverses the role of "alt" and "ref" correspondingly so that the output remains the same as before these changes (the original outputs were correct as validated against the plink1 "ped" text genotypes).
>   * All documentation was updated to reflect these changes.

Thank you for your answer!!!
