### ISSUE TITLE
genio cannot read a .bed file

### ISSUE THREAD

**Issue by richelbilderbeek** [OchoaLab/genio#3]
Dear genio maintainer,

I am a happy user of genio, so thanks for writing it!

Unexpectedly, I came across a .bed file that cannot be loaded by genio, yet can be loaded by [the ARTP2 CRAN package](https://github.com/zhangh12/ARTP2). Below is a reprex to demonstrate this.

I hope you'll fix this, as I -a fellow package maintainer- prefer to depend on less packages over more :-)

Thanks and cheers, Richel

```r
# Download example files to temp folder
temp_folder <- tempfile()
bed_filename <- file.path(temp_folder, "file.bed")
bim_filename <- file.path(temp_folder, "file.bim")
fam_filename <- file.path(temp_folder, "file.fam")
dir.create(temp_folder, showWarnings = FALSE, recursive = TRUE)
download.file(
  "https://github.com/kausmees/GenoCAE/blob/master/example_tiny/HumanOrigins249_tiny.bed?raw=true",
  destfile = bed_filename
)
download.file(
  "https://github.com/kausmees/GenoCAE/blob/master/example_tiny/HumanOrigins249_tiny.bim?raw=true",
  destfile = bim_filename
)
download.file(
  "https://github.com/kausmees/GenoCAE/blob/master/example_tiny/HumanOrigins249_tiny.fam?raw=true",
  destfile = fam_filename
)

# Works with ARTP2
bed_table <- ARTP2::read.bed(
  bed = bed_filename,
  bim = bim_filename,
  fam = fam_filename
)

# Does not work with genio
bim_table <- genio::read_bim(bim_filename)
fam_table <- genio::read_bim(fam_filename)
genio::read_bed(
  bed_filename,
  names_loci = bim_table$id,
  names_ind = fam_table$id
)

# Clean up
unlink(temp_folder)
```

**Comment by alexviiia** [comment]
Hi again Richel,

I removed the check that triggered the error you were observing.  The issue was that BED files sometimes have "pads" (each byte can hold individual for up to 4 people, but if the data doesn't have a multiple of 4 of individuals, then the rest of the final byte of each locus is "padded" with dummy bits).  My code required these pads to be zero bits only (I thought I had read that plink required that), and in my tests I hadn't encountered files that failed that test.  However, I verified that the files you provided above don't fail when processed by `plink2` or using the `BEDMatrix` R package (my other favorite choice other than `genio`), so that convinced me that it's ok to just completely ignore the pad values.  I verified that the code works on the specific BED file you provided.  That fix is available immediately on this GitHub version, not sure when it'll make its way to CRAN (I tend to wait months between updates, let me know if this makes a difference to you).

By the way, with `genio` you can also load a standard "base".{bed,bim,fam} trio using:
```
data <- read_plink("base")
data$X # genotypes
data$bim # bim table
data$fam # fam table
```
In addition to less typing, doing it this way performs additional checks and transfers the loci/individual IDs automatically.  It does currently require that the "base" be shared and the extensions be exactly bed, bim, and fam.

Thanks for your reports!
-Alex

**Comment by richelbilderbeek** [comment]
Hi Alex, thanks so much for your work of art! That it's on GitHub only for now is fine :-)
